### ISSUE TITLE
Vytvorit okno s nastaveniami

### ISSUE THREAD

**Issue by samod1** [samod1/filipSOC#75]
V databaze je tabulka _**tbl_settings**_ treba pre nu nakreslit okno to doplnim neskor.

@samod1 nakreslit obrazovku pre toto
@Filipenzo  treba spravit obrazovku s nastaveniami, kde sa zatial bude nastavovat hodnota miesta merania.

**Comment by samod1** [comment]
Posielam navrh obrazovky s nastaveniami
![Nastavenia](https://user-images.githubusercontent.com/29199911/198248909-5745b5d4-7940-4de2-9c7a-0a23a77a0fd1.jpg)


**_tbl_settings_** bude mat strukturu

| **Setting**    | **Option** |
|----------------|------------|
| Hodiny         | a          |
| Miesto_meranie | 240000     |
| Jednotky       | metricke   |

S tym, ze budeme musiet spravit cudzie kluce pre jednotky a aj obce.

**Comment by Filipenzo** [comment]
použil som enum_okres lebo  enum_obce má veľa údajov

**Comment by samod1** [comment]
> použil som enum_okres lebo  enum_obce má veľa údajov  

Najdem nejaké lepšie riešenie. Cez nejaké AJAX. A spravíme nejaký podmienený select ďalším selectom. Zatiaľ to nechaj otvorené. 😃

**Comment by samod1** [comment]
https://youtu.be/neZTTWJ98-0

Skús tento tutoriál kuknúť.

**Comment by samod1** [comment]
Kod krajny SK je 703

**Comment by samod1** [comment]
Okno je vytvorene parcialne bugy budu povytvarane
