### ISSUE TITLE
pre mazanie udajov spravit $_GET rolu

### ISSUE THREAD

**Issue by samod1** [samod1/filipSOC#78]
Prosim sprav rolu admin, ktora sa bude volat **getom**. V skole mi to hovorili, aby sme to tam dorobili, aby nemohli random pouzivatelia vymazavat udaje. Neskor integrujeme keycloak.

[https://www.keycloak.org/](url)
 
Priklad

`www.filip.samod.sk?rola=admin`

**Comment by samod1** [comment]
[c74524b](https://github.com/samod1/filipSOC/pull/87/commits/c74524b79c58e4f6b92ea83fced77e4ef24b65b9) podla tohoto

**Comment by Filipenzo** [comment]
je tam bug že keď není nastavená rola tak píše error

**Comment by samod1** [comment]
To je len warning ale dá sa odstrániť pridaním podmienky **if(isset($_GET["rola"]){
...}
Else
Setni rolu na user**
